### ISSUE TITLE
Настройка параметров слайдера

### ISSUE THREAD

**Issue by Kedoper** [itchief/how-to#1]
Привет, было бы очень кстати сделать возможность настройки слайдера через указание параметров. А то вдруг нужно будет на одной странице сделать несколько слайдеров.

Если это в данный момент можно сделать, то как? А то я что-то не понял.

Использую [данный ](https://github.com/itchief/how-to/blob/master/slider/main.js) код слайдера

**Comment by itchief** [comment]
Привет!
[Здесь](https://itchief.ru/javascript/how-to-create-slider) можно более подробно почитать про этот слайдер. Там же есть различные примеры.

Как разместить на странице несколько слайдеров можно ознакомиться в [этом рецепте](https://itchief.ru/javascript/how-to-create-slider#comment-6952).
